/**
 * Mishloha (משלוחה / דיב אנד רד) PDF invoice parser
 *
 * Parses tax invoices (חשבונית מס) from Mishloha / Div & Red Projects Ltd.
 * These are charges TO the franchisee for delivery platform services.
 *
 * Document structure:
 * - Header: company name, ח.פ., customer (לכבוד), invoice number, date
 * - Line items table: מק"ט | פירוט | כמות | מחיר | סכום
 *   Each item may have a discount line (הנחת שורה) reducing the amount
 * - Footer: pre-VAT total (סה"כ חייב במע"מ), VAT amount, grand total (סה"כ)
 *
 * Generated by "Hyp | EasyCount" invoicing system.
 *
 * Key data points:
 * - Franchisee name from "לכבוד:" line
 * - Invoice number (חשבונית מס מספר)
 * - Period from date range (מתאריך ... עד תאריך)
 * - Pre-VAT total = totalAmount = commissionAmount
 * - Grand total (incl. VAT) = netAmount
 */

import { createRequire } from "node:module";
import type { ClientDocumentProcessingResult, ClientParsedLineItem } from "./types";
import { extractAllocationNumber } from "./extract-allocation-number";

// Import from /lib/pdf-parse.js directly — the package's index.js runs a
// debug file-read at module load when `module.parent` is null (breaks Turbopack builds).
const pdfParse = createRequire(import.meta.url)("pdf-parse/lib/pdf-parse.js");

/**
 * Dynamic imports for OCR dependencies (pdfjs-dist + tesseract.js + sharp).
 * String-variable imports prevent Turbopack from trying to resolve
 * WASM / native / ESM packages at build time.
 */
const PDFJS_MODULE = "pdfjs-dist/legacy/build/pdf.mjs";
const TESSERACT_MODULE = "tesseract.js";
const SHARP_MODULE = "sharp";

async function loadPdfjs() {
  return import(/* webpackIgnore: true */ PDFJS_MODULE);
}

async function loadTesseract() {
  return import(/* webpackIgnore: true */ TESSERACT_MODULE);
}

async function loadSharp() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const mod: any = await import(/* webpackIgnore: true */ SHARP_MODULE);
  return (mod.default ?? mod) as typeof import("sharp");
}

/**
 * Extract the first embedded image from a PDF using pdfjs-dist and encode
 * it as PNG so tesseract can read it. jsPDF-generated invoices embed the
 * whole page as a single image, and pdfjs returns decoded RGBA pixel data
 * which tesseract cannot consume directly — it needs an encoded format
 * (PNG/JPEG). We re-encode via sharp here.
 *
 * Returns a PNG Buffer, or null if no image was found on page 1.
 */
async function extractImageFromPDF(buffer: Buffer): Promise<Buffer | null> {
  const pdfjsLib = await loadPdfjs();

  const doc = await pdfjsLib.getDocument({ data: new Uint8Array(buffer) })
    .promise;
  const page = await doc.getPage(1);
  const ops = await page.getOperatorList();

  const OPS = pdfjsLib.OPS;
  for (let i = 0; i < ops.fnArray.length; i++) {
    if (ops.fnArray[i] === OPS.paintImageXObject) {
      const imgName = ops.argsArray[i][0] as string;
      const imgData = await new Promise<{
        data: Uint8Array;
        width: number;
        height: number;
        kind?: number;
      } | null>((resolve) => page.objs.get(imgName, resolve));

      if (imgData?.data && imgData.width && imgData.height) {
        const { data, width, height } = imgData;
        // pdfjs may hand back RGB (3 channels) or RGBA (4 channels). Derive
        // it from the buffer length so sharp can consume the raw bitmap.
        const pixels = width * height;
        const rawChannels = data.length / pixels;
        if (rawChannels !== 3 && rawChannels !== 4) {
          // Non-standard (e.g. grayscale, CMYK) — skip, let caller try
          // whole-page rendering instead.
          continue;
        }
        const sharp = await loadSharp();
        return await sharp(Buffer.from(data), {
          raw: {
            width,
            height,
            channels: rawChannels as 3 | 4,
          },
        })
          .png()
          .toBuffer();
      }
    }
  }
  return null;
}

/**
 * Render page 1 of a PDF to a PNG image using pdfjs-dist's SVG back end.
 * Fallback for PDFs where no XObject image is present (e.g. text-rendered
 * as vector drawings) so we still have something to OCR. Returns null if
 * rendering is unavailable in the current environment.
 */
async function renderPdfPageToPng(buffer: Buffer): Promise<Buffer | null> {
  try {
    const pdfjsLib = await loadPdfjs();
    const doc = await pdfjsLib.getDocument({ data: new Uint8Array(buffer) })
      .promise;
    const page = await doc.getPage(1);
    // 2x scale for better OCR accuracy on small fonts
    const viewport = page.getViewport({ scale: 2 });
    const width = Math.ceil(viewport.width);
    const height = Math.ceil(viewport.height);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const canvasMod: any = await import(
      /* webpackIgnore: true */ "@napi-rs/canvas"
    ).catch(() => null);
    if (!canvasMod) return null;

    const canvas = canvasMod.createCanvas(width, height);
    const ctx = canvas.getContext("2d");
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, width, height);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await page.render({ canvasContext: ctx as any, viewport }).promise;
    return canvas.toBuffer("image/png");
  } catch {
    return null;
  }
}

/**
 * Run OCR on an image buffer using tesseract.js with Hebrew + English.
 */
async function ocrImage(imageBuffer: Buffer): Promise<string> {
  const tess = await loadTesseract();
  const recognize = tess.default?.recognize ?? tess.recognize;
  const { data } = await recognize(imageBuffer, "heb+eng");
  return data.text;
}

/**
 * Parse a Mishloha PDF invoice.
 * Extracts totals, franchisee name, and period from a Hyp/EasyCount invoice.
 */
export async function parseMishlohaFile(
  buffer: Buffer,
  _mimeType: string
): Promise<ClientDocumentProcessingResult> {
  const errors: string[] = [];
  const warnings: string[] = [];

  try {
    const pdfData = await pdfParse(buffer);
    let text = pdfData.text as string;

    // jsPDF-generated invoices embed content as a page-sized image and have
    // no text layer. Fall back to OCR and feed the OCR text through the
    // same parsing pipeline (labels in OCR output are in normal LTR order,
    // so the LTR patterns below handle them).
    if (!text || text.length < 50) {
      try {
        let imageBuffer = await extractImageFromPDF(buffer);
        if (!imageBuffer) {
          imageBuffer = await renderPdfPageToPng(buffer);
        }
        if (!imageBuffer) {
          errors.push("לא ניתן לחלץ טקסט או תמונה מקובץ ה-PDF של משלוחה");
          return { success: false, data: null, errors, warnings };
        }
        const ocrText = await ocrImage(imageBuffer);
        if (!ocrText || ocrText.length < 50) {
          errors.push("OCR לא הצליח לחלץ טקסט מחשבונית משלוחה");
          return { success: false, data: null, errors, warnings };
        }
        warnings.push("טקסט חולץ באמצעות OCR (חשבונית jsPDF)");
        text = ocrText;
      } catch (ocrError) {
        errors.push(
          `חילוץ טקסט נכשל ו-OCR לא זמין: ${ocrError instanceof Error ? ocrError.message : String(ocrError)}`
        );
        return { success: false, data: null, errors, warnings };
      }
    }

    const lines = text.split("\n").map((l) => l.trim()).filter(Boolean);

    // ---------------------------------------------------------------
    // Franchisee name
    // ---------------------------------------------------------------
    // CRITICAL: The franchisee is the ISSUER of the invoice (at the top),
    // NOT the recipient (who is "משלוחה" — the client being invoiced).
    //
    // Invoice structure:
    //   קסטרא טומאי בע"מ        ← ISSUER (franchisee, first line)
    //   ח.פ. 514177212           ← issuer tax ID
    //   ...
    //   לכבוד: משלוחה (דיב אנד רד)  ← RECIPIENT (the client, NOT the franchisee)
    //
    // Strategy: extract the first Hebrew business name BEFORE "לכבוד" appears.
    let franchiseeName = "";
    // Find where "לכבוד" appears and search BEFORE it for the issuer
    const lekavodIdx = lines.findIndex(
      (l) => l.match(/לכבוד/) || l.match(/דובכל/)
    );
    const searchLines =
      lekavodIdx > 0 ? lines.slice(0, lekavodIdx) : lines.slice(0, 10);

    // Detect document direction by inspecting the issuer block (lines
    // BEFORE "לכבוד"). When the issuer is a KNOWN CLIENT (HAAT Delivery,
    // Mishlocha, Wolt Enterprises, ...), this is a commission_invoice
    // (client → franchisee) and the franchisee lives in the "לכבוד"
    // recipient block. Otherwise it's an income invoice (franchisee →
    // client) and the franchisee is the issuer at the top — recipient
    // extraction must be skipped to avoid pulling the client name.
    const KNOWN_CLIENT_TOKENS = [
      "haat delivery",
      "wolt enterprises",
      "wolt",
      "משלוחה",
      "האאט דילברי",
      "האאט",
      "סיבוס",
      "פלאקסי",
      "תן ביס",
    ];
    const issuerBlobLower = searchLines.join(" ").toLowerCase();
    const issuerIsKnownClient = KNOWN_CLIENT_TOKENS.some((tok) =>
      issuerBlobLower.includes(tok.toLowerCase())
    );

    if (lekavodIdx >= 0 && issuerIsKnownClient) {
      // Commission invoice: franchisee is on the "לכבוד:" line itself
      // (NOT before it — that's the issuer = Mishloha).
      // Two layouts seen in production:
      //   A. Same-line:  "לכבוד: פאט ויני עזריאלי בע\"מ"
      //   B. Multi-line: "לכבוד:" on its own line, recipient on the next.
      //                   HAAT central commission invoices SI* use this
      //                   layout (incident 2026-05-10: SI266010419 was
      //                   mis-attributed to ויני רגבה because the parser
      //                   stripped "לכבוד:" off an empty-after-strip line
      //                   and fell through to the legacy issuer-side
      //                   extraction, returning "האאט דילברי בע\"מ").
      const lekavodLine = lines[lekavodIdx];
      const stripLabel = (s: string) =>
        s
          .replace(/""/g, '"')
          .replace(/^.*?לכבוד[:\s]*/, "")
          .replace(/^"+|"+$/g, "")
          .trim();
      const sameLineAfterLabel = stripLabel(lekavodLine);
      // If layout A produced a non-empty value, use it as-is.
      // If layout B (label-on-own-line), pull from the next non-empty line.
      let afterLabel = sameLineAfterLabel;
      if (!afterLabel) {
        for (let off = 1; off <= 3 && lekavodIdx + off < lines.length; off++) {
          const nextLine = lines[lekavodIdx + off];
          if (!nextLine || /^[\d\s./:]+$/.test(nextLine)) continue;
          afterLabel = nextLine.replace(/""/g, '"').trim();
          if (afterLabel.length > 0) break;
        }
      }
      // (Redundant client-token guard removed — outer `issuerIsKnownClient`
      // gate already ensures we only enter this block for commission
      // invoices, where the recipient is always the franchisee.)

      // 1. Prefer a legal-entity name ending in בע"מ
      const bizMatch = afterLabel.match(
        /([\u0590-\u05FF][\u0590-\u05FF\s"'״]+?(?:בע"מ|בעמ|בע״מ))/
      );
      if (bizMatch) {
        franchiseeName = bizMatch[1].trim();
      }

      // 2. Fall back to the branch/DBA name (Hebrew segment without parens)
      if (!franchiseeName) {
        const segments = afterLabel
          .split(/[()]/g)
          .map((s) => s.trim())
          .filter(Boolean);
        const branchCandidate = segments.find((s) =>
          /^([\u0590-\u05FF][\u0590-\u05FF\s"'״]+$)/.test(s)
        );
        if (branchCandidate) {
          franchiseeName = branchCandidate;
        }
      }

      // 3. Last resort: stripped of parens/quotes
      if (!franchiseeName) {
        const cleaned = afterLabel.replace(/["()]/g, "").trim();
        if (cleaned.length >= 3) franchiseeName = cleaned;
      }
    }

    // Legacy fallback for older sales-invoice layouts where the franchisee
    // is the ISSUER (top of doc, before "לכבוד"). Used only if the new
    // recipient-based extraction returned nothing.
    if (!franchiseeName) {
      const searchLines =
        lekavodIdx > 0 ? lines.slice(0, lekavodIdx) : lines.slice(0, 10);
      for (const line of searchLines) {
        const bizMatch = line.match(
          /^([\u0590-\u05FF][\u0590-\u05FF\s"'״]+?(?:בע"מ|בעמ|בע״מ))/
        );
        if (bizMatch) {
          franchiseeName = bizMatch[1].trim();
          break;
        }
      }
    }

    if (!franchiseeName) {
      warnings.push("לא זוהה שם הזכיין מחשבונית העמלה");
    }

    // ---------------------------------------------------------------
    // Invoice number
    // ---------------------------------------------------------------
    let invoiceNumber = "";
    // Normal order: "חשבונית מס מספר 153464"
    const invMatch = text.match(/חשבונית\s+מס\s+מספר\s+(\d+)/);
    if (invMatch) {
      invoiceNumber = invMatch[1];
    }
    // Visual reversed: "153464 רפסמ סמ תינובשח"
    if (!invoiceNumber) {
      const invRevMatch = text.match(/(\d+)\s+רפסמ\s+סמ\s+תינובשח/);
      if (invRevMatch) {
        invoiceNumber = invRevMatch[1];
      }
    }
    // HAAT centralized invoices ("חשבונית מס מרכזת SI266013293") carry an
    // alphanumeric SI number, glued to the label in visual-RTL output
    // (e.g. "…SI266013293חשבונית מס מרכז" — digits BEFORE the label), which
    // the numeric patterns above and the loose fallback below can't reach.
    // Real MISHLOCHA invoices use numeric numbers, so this is HAAT-only.
    if (!invoiceNumber) {
      const siMatch = text.match(/SI\d{6,}/i);
      if (siMatch) {
        invoiceNumber = siMatch[0].toUpperCase();
      }
    }
    // Fallback: any number near "חשבונית"
    if (!invoiceNumber) {
      const invFallback = text.match(/חשבונית.*?(\d{4,})/);
      if (invFallback) {
        invoiceNumber = invFallback[1];
      }
    }

    // ---------------------------------------------------------------
    // Period extraction
    // ---------------------------------------------------------------
    let periodMonth: number | undefined;
    let periodYear: number | undefined;

    // Pattern: "מתאריך DD/MM/YYYY עד תאריך DD/MM/YYYY"
    const periodMatch = text.match(
      /מתאריך\s+(\d{2})\/(\d{2})\/(\d{4})\s+עד\s+תאריך\s+(\d{2})\/(\d{2})\/(\d{4})/
    );
    if (periodMatch) {
      periodMonth = parseInt(periodMatch[2]);
      periodYear = parseInt(periodMatch[3]);
    }

    // Visual reversed: "YYYY/MM/DD ךיראתמ ... YYYY/MM/DD ךיראת דע"
    if (!periodMonth) {
      const periodRevMatch = text.match(
        /(\d{2})\/(\d{2})\/(\d{4})\s+ךיראתמ/
      );
      if (periodRevMatch) {
        periodMonth = parseInt(periodRevMatch[2]);
        periodYear = parseInt(periodRevMatch[3]);
      }
    }

    // Fallback: date from "תאריך: DD/MM/YYYY"
    if (!periodMonth) {
      const dateMatch = text.match(/תאריך[:\s]+(\d{2})\/(\d{2})\/(\d{4})/);
      if (dateMatch) {
        periodMonth = parseInt(dateMatch[2]);
        periodYear = parseInt(dateMatch[3]);
      }
    }
    // Visual reversed date: "YYYY/MM/DD :ךיראת"
    if (!periodMonth) {
      const dateRevMatch = text.match(/(\d{2})\/(\d{2})\/(\d{4})\s*:?\s*ךיראת/);
      if (dateRevMatch) {
        periodMonth = parseInt(dateRevMatch[2]);
        periodYear = parseInt(dateRevMatch[3]);
      }
    }
    // Display-order RTL (label after value, Hebrew NOT char-reversed):
    // "DD/MM/YYYY :תאריך". Seen on ezcount-issued HAAT income invoices
    // where pdf-parse keeps Hebrew logical but emits the line value-first.
    if (!periodMonth) {
      const dateRtlMatch = text.match(
        /(\d{2})\/(\d{2})\/(\d{4})\s+:?\s*תאריך/
      );
      if (dateRtlMatch) {
        periodMonth = parseInt(dateRtlMatch[2]);
        periodYear = parseInt(dateRtlMatch[3]);
      }
    }

    // ---------------------------------------------------------------
    // Totals extraction
    // ---------------------------------------------------------------
    // IMPORTANT: mPDF-generated invoices (ezcount) output RTL text where
    // the amount appears on the line BEFORE the label:
    //     ₪9,886.64
    //     סה"כ חייב במע"מ:
    // Check mPDF patterns FIRST, fall back to LTR patterns.
    let preVatTotal = 0;
    let vatAmount = 0;
    let grandTotal = 0;

    // Pre-VAT total
    // mPDF RTL: "₪9,886.64\nסה"כ חייב במע"מ:" (amount BEFORE label)
    const preVatMpdfMatch = text.match(
      /₪?([\d,]+\.\d{2})\s*\n\s*סה"כ\s+חייב\s+במע"מ/
    );
    if (preVatMpdfMatch) {
      preVatTotal = parseFloat(preVatMpdfMatch[1].replace(/,/g, ""));
    }
    // LTR: "סה"כ חייב במע"מ: ₪756.06"
    if (preVatTotal === 0) {
      const preVatMatch = text.match(
        /סה"כ\s+חייב\s+במע"מ[:\s]*(?:[^\d\n]*\s)?₪?\s*([\d,]+\.\d{2})/
      );
      if (preVatMatch) {
        preVatTotal = parseFloat(preVatMatch[1].replace(/,/g, ""));
      }
    }
    // Visual reversed: '756.06₪ :מ"עמב בייח כ"הס'
    if (preVatTotal === 0) {
      const preVatRevMatch = text.match(
        /([\d,]+\.?\d*)\s*₪?\s*:?\s*מ"עמב\s+בייח\s+כ"הס/
      );
      if (preVatRevMatch) {
        preVatTotal = parseFloat(preVatRevMatch[1].replace(/,/g, ""));
      }
    }

    // VAT amount
    // mPDF RTL: "₪1,779.59:18.00%מע"מ" (amount first, then :18%מע"מ)
    const vatMpdfMatch = text.match(
      /₪?([\d,]+\.\d{2}):[\d.]+%\s*מע"מ/
    );
    if (vatMpdfMatch) {
      vatAmount = parseFloat(vatMpdfMatch[1].replace(/,/g, ""));
    }
    // LTR: "מע"מ 18.00%: ₪136.09"
    if (vatAmount === 0) {
      const vatMatch = text.match(
        /מע"מ\s+[\d.]+%[:\s]*(?:[^\d\n]*\s)?₪?\s*([\d,]+\.\d{2})/
      );
      if (vatMatch) {
        vatAmount = parseFloat(vatMatch[1].replace(/,/g, ""));
      }
    }
    // Reversed: '136.09₪ :%00.81 מ"עמ'
    if (vatAmount === 0) {
      const vatRevMatch = text.match(
        /([\d,]+\.?\d*)\s*₪?\s*:?\s*%[\d.]+\s+מ"עמ/
      );
      if (vatRevMatch) {
        vatAmount = parseFloat(vatRevMatch[1].replace(/,/g, ""));
      }
    }

    // Grand total
    // mPDF RTL: "₪11,666.23\nסה"כ:" (amount BEFORE a BARE "סה"כ:" label
    // that has nothing after it on its line).
    // Require end-of-line after the colon so we don't accidentally match
    // an OCR line like "סה"כ: ₪1,616.81" — where the label has the amount
    // on the SAME line, and the line BEFORE is the VAT amount. Without
    // this guard, grandTotal is silently set to the VAT figure.
    const grandMpdfMatch = text.match(
      /₪?([\d,]+\.\d{2})\s*\n\s*סה"כ:\s*(?=\n|$)/
    );
    if (grandMpdfMatch) {
      grandTotal = parseFloat(grandMpdfMatch[1].replace(/,/g, ""));
    }
    // LTR: "סה"כ: ₪892.15"
    if (grandTotal === 0) {
      const grandTotalMatches = [
        ...text.matchAll(/סה"כ:[:\s]*(?:[^\d\n]*\s)?₪?\s*([\d,]+\.\d{2})/g),
      ];
      for (let i = grandTotalMatches.length - 1; i >= 0; i--) {
        const val = parseFloat(grandTotalMatches[i][1].replace(/,/g, ""));
        if (val > 0 && val !== preVatTotal) {
          grandTotal = val;
          break;
        }
      }
    }

    // Reversed grand total: look for 'כ"הס' near numbers
    if (grandTotal === 0) {
      const grandRevMatches = [
        ...text.matchAll(/([\d,]+\.?\d*)\s*₪?\s*:?\s*כ"הס/g),
      ];
      for (let i = grandRevMatches.length - 1; i >= 0; i--) {
        const val = parseFloat(grandRevMatches[i][1].replace(/,/g, ""));
        if (val > 0 && val !== preVatTotal) {
          grandTotal = val;
          break;
        }
      }
    }

    // If we have pre-VAT and VAT but no grand total, calculate it
    if (grandTotal === 0 && preVatTotal > 0 && vatAmount > 0) {
      grandTotal = preVatTotal + vatAmount;
    }

    // If we have grand total and VAT but no pre-VAT, calculate it
    if (preVatTotal === 0 && grandTotal > 0 && vatAmount > 0) {
      preVatTotal = grandTotal - vatAmount;
    }

    // If we only have grand total, estimate pre-VAT (18% VAT)
    if (preVatTotal === 0 && grandTotal > 0) {
      preVatTotal = Math.round((grandTotal / 1.18) * 100) / 100;
      warnings.push("סכום לפני מע\"מ חושב מהסכום הכולל (18% מע\"מ)");
    }

    // ---------------------------------------------------------------
    // Line items extraction (best-effort)
    // ---------------------------------------------------------------
    const lineItems: ClientParsedLineItem[] = [];

    // Look for line items with מק"ט code pattern: "NNNN: description"
    const lineItemPattern = /(\d{1,5}):\s*([\u0590-\u05FF\s_\w"']+)/g;
    let itemMatch;
    while ((itemMatch = lineItemPattern.exec(text)) !== null) {
      const description = itemMatch[2].trim();
      if (description.length > 2) {
        lineItems.push({
          date: null,
          description: `${itemMatch[1]}: ${description}`,
          amount: 0, // Individual amounts are hard to reliably extract
          commission: 0,
        });
      }
    }

    // ---------------------------------------------------------------
    // Validation
    // ---------------------------------------------------------------
    if (preVatTotal === 0 && grandTotal === 0) {
      // Last resort: find the largest numbers in the document
      const allNumbers = [...text.matchAll(/([\d,]+\.\d{2})/g)]
        .map((m) => parseFloat(m[1].replace(/,/g, "")))
        .filter((n) => n > 0);

      if (allNumbers.length > 0) {
        allNumbers.sort((a, b) => b - a);
        grandTotal = allNumbers[0];
        // Second largest is likely the pre-VAT total
        if (allNumbers.length > 1) {
          preVatTotal = allNumbers[1];
        }
        warnings.push("הסכומים חולצו מהמספר הגדול ביותר במסמך - יש לאמת");
      } else {
        errors.push("לא נמצאו סכומים בחשבונית משלוחה");
        return { success: false, data: null, errors, warnings };
      }
    }

    if (!franchiseeName) {
      warnings.push("לא זוהה שם הזכיין מהמסמך");
    }

    if (!periodMonth) {
      warnings.push("לא זוהתה תקופת החשבונית");
    }

    // Calculate derived amounts if needed
    if (grandTotal > 0 && preVatTotal === 0 && vatAmount > 0) {
      preVatTotal = grandTotal - vatAmount;
    }
    if (preVatTotal > 0 && grandTotal === 0 && vatAmount > 0) {
      grandTotal = preVatTotal + vatAmount;
    }

    // Israeli tax allocation number (מספר הקצאה) — only present on invoices
    // over the threshold (₪10,000 today, dropping to ₪5,000). undefined when absent.
    const allocationNumber = extractAllocationNumber(text);

    return {
      success: true,
      data: {
        franchiseeName: franchiseeName || "לא זוהה",
        // totalAmount = grand total incl VAT (what the franchisee is owed in total)
        totalAmount: grandTotal || preVatTotal,
        // commissionAmount = VAT portion (NOT a commission to Mishloha —
        // Mishloha's commission is already baked into pre-VAT via line deductions)
        commissionAmount: vatAmount,
        commissionRate: vatAmount > 0 && preVatTotal > 0
          ? Math.round((vatAmount / preVatTotal) * 10000) / 100
          : 0,
        // netAmount = pre-VAT subtotal (after credit commission + customer comp deductions)
        netAmount: preVatTotal || grandTotal,
        periodMonth,
        periodYear,
        // Surface the extracted invoice number so it propagates to
        // client_document.invoice_number → Hashavshevet "אסמכתא 2"
        // column. Was previously embedded only in the line-item
        // description, which left the column blank for HAAT/Mishlocha
        // exports (Reut 2026-05-10).
        invoiceNumber: invoiceNumber || undefined,
        allocationNumber,
        lineItems:
          lineItems.length > 0
            ? lineItems
            : [
                {
                  date: null,
                  description: `חשבונית מס ${invoiceNumber || "משלוחה"}`,
                  amount: preVatTotal,
                  commission: preVatTotal,
                },
              ],
        rawText: text,
      },
      errors,
      warnings,
    };
  } catch (error) {
    errors.push(
      `שגיאה בקריאת PDF משלוחה: ${error instanceof Error ? error.message : String(error)}`
    );
    return { success: false, data: null, errors, warnings };
  }
}
