/**
 * Mishloha (משלוחה / דיב אנד רד) PDF invoice parser
 *
 * Parses tax invoices (חשבונית מס) from Mishloha / Div & Red Projects Ltd.
 * These are charges TO the franchisee for delivery platform services.
 *
 * Document structure:
 * - Header: company name, ח.פ., customer (לכבוד), invoice number, date
 * - Line items table: מק"ט | פירוט | כמות | מחיר | סכום
 *   Each item may have a discount line (הנחת שורה) reducing the amount
 * - Footer: pre-VAT total (סה"כ חייב במע"מ), VAT amount, grand total (סה"כ)
 *
 * Generated by "Hyp | EasyCount" invoicing system.
 *
 * Key data points:
 * - Franchisee name from "לכבוד:" line
 * - Invoice number (חשבונית מס מספר)
 * - Period from date range (מתאריך ... עד תאריך)
 * - Pre-VAT total = totalAmount = commissionAmount
 * - Grand total (incl. VAT) = netAmount
 */

import type { ClientDocumentProcessingResult, ClientParsedLineItem } from "./types";

// eslint-disable-next-line @typescript-eslint/no-require-imports
const pdfParse = require("pdf-parse");

/**
 * Parse a Mishloha PDF invoice.
 * Extracts totals, franchisee name, and period from a Hyp/EasyCount invoice.
 */
export async function parseMishlohaFile(
  buffer: Buffer,
  _mimeType: string
): Promise<ClientDocumentProcessingResult> {
  const errors: string[] = [];
  const warnings: string[] = [];

  try {
    const data = await pdfParse(buffer);
    const text = data.text as string;

    if (!text || text.length < 50) {
      errors.push("לא ניתן לחלץ טקסט מקובץ ה-PDF של משלוחה");
      return { success: false, data: null, errors, warnings };
    }

    const lines = text.split("\n").map((l) => l.trim()).filter(Boolean);

    // ---------------------------------------------------------------
    // Franchisee name
    // ---------------------------------------------------------------
    // The "לכבוד:" line contains the franchisee name.
    // In pdf-parse RTL output it may appear as:
    //   "פאט ויני ביג רגבה(ויני רגבה בע"מ)" or similar
    // We look for "לכבוד" or the reversed visual form "דובכל"
    let franchiseeName = "";
    for (const line of lines) {
      // LTR-rendered "לכבוד:" pattern
      const lekavod = line.match(/לכבוד[:\s]+(.+)/);
      if (lekavod) {
        franchiseeName = lekavod[1]
          .replace(/[,،]/g, "")
          .replace(/ח\.פ\..*$/, "")
          .replace(/ת\.ז\..*$/, "")
          .trim();
        break;
      }
      // Visual-order reversed: "דובכל" at end of line
      const reversed = line.match(/(.+?)\s*:?\s*דובכל/);
      if (reversed) {
        franchiseeName = reversed[1]
          .replace(/[,،]/g, "")
          .replace(/\.פ\.ח.*$/, "")
          .replace(/\.ז\.ת.*$/, "")
          .trim();
        break;
      }
    }

    // ---------------------------------------------------------------
    // Invoice number
    // ---------------------------------------------------------------
    let invoiceNumber = "";
    // Normal order: "חשבונית מס מספר 153464"
    const invMatch = text.match(/חשבונית\s+מס\s+מספר\s+(\d+)/);
    if (invMatch) {
      invoiceNumber = invMatch[1];
    }
    // Visual reversed: "153464 רפסמ סמ תינובשח"
    if (!invoiceNumber) {
      const invRevMatch = text.match(/(\d+)\s+רפסמ\s+סמ\s+תינובשח/);
      if (invRevMatch) {
        invoiceNumber = invRevMatch[1];
      }
    }
    // Fallback: any number near "חשבונית"
    if (!invoiceNumber) {
      const invFallback = text.match(/חשבונית.*?(\d{4,})/);
      if (invFallback) {
        invoiceNumber = invFallback[1];
      }
    }

    // ---------------------------------------------------------------
    // Period extraction
    // ---------------------------------------------------------------
    let periodMonth: number | undefined;
    let periodYear: number | undefined;

    // Pattern: "מתאריך DD/MM/YYYY עד תאריך DD/MM/YYYY"
    const periodMatch = text.match(
      /מתאריך\s+(\d{2})\/(\d{2})\/(\d{4})\s+עד\s+תאריך\s+(\d{2})\/(\d{2})\/(\d{4})/
    );
    if (periodMatch) {
      periodMonth = parseInt(periodMatch[2]);
      periodYear = parseInt(periodMatch[3]);
    }

    // Visual reversed: "YYYY/MM/DD ךיראתמ ... YYYY/MM/DD ךיראת דע"
    if (!periodMonth) {
      const periodRevMatch = text.match(
        /(\d{2})\/(\d{2})\/(\d{4})\s+ךיראתמ/
      );
      if (periodRevMatch) {
        periodMonth = parseInt(periodRevMatch[2]);
        periodYear = parseInt(periodRevMatch[3]);
      }
    }

    // Fallback: date from "תאריך: DD/MM/YYYY"
    if (!periodMonth) {
      const dateMatch = text.match(/תאריך[:\s]+(\d{2})\/(\d{2})\/(\d{4})/);
      if (dateMatch) {
        periodMonth = parseInt(dateMatch[2]);
        periodYear = parseInt(dateMatch[3]);
      }
    }
    // Visual reversed date: "YYYY/MM/DD :ךיראת"
    if (!periodMonth) {
      const dateRevMatch = text.match(/(\d{2})\/(\d{2})\/(\d{4})\s*:?\s*ךיראת/);
      if (dateRevMatch) {
        periodMonth = parseInt(dateRevMatch[2]);
        periodYear = parseInt(dateRevMatch[3]);
      }
    }

    // ---------------------------------------------------------------
    // Totals extraction
    // ---------------------------------------------------------------
    let preVatTotal = 0;
    let vatAmount = 0;
    let grandTotal = 0;

    // Pre-VAT total: 'סה"כ חייב במע"מ: ₪756.06'
    // Normal order
    const preVatMatch = text.match(
      /סה"כ\s+חייב\s+במע"מ[:\s]*(₪?)\s*([\d,]+\.?\d*)/
    );
    if (preVatMatch) {
      preVatTotal = parseFloat(preVatMatch[2].replace(/,/g, ""));
    }
    // Visual reversed: '756.06₪ :מ"עמב בייח כ"הס'
    if (preVatTotal === 0) {
      const preVatRevMatch = text.match(
        /([\d,]+\.?\d*)\s*₪?\s*:?\s*מ"עמב\s+בייח\s+כ"הס/
      );
      if (preVatRevMatch) {
        preVatTotal = parseFloat(preVatRevMatch[1].replace(/,/g, ""));
      }
    }
    // Alternative: look for "חייב במע" near a number
    if (preVatTotal === 0) {
      const altPreVat = text.match(
        /חייב\s+במע.*?([\d,]+\.\d{2})/
      );
      if (altPreVat) {
        preVatTotal = parseFloat(altPreVat[1].replace(/,/g, ""));
      }
    }

    // VAT amount: 'מע"מ 18.00%: ₪136.09'
    const vatMatch = text.match(
      /מע"מ\s+[\d.]+%[:\s]*(₪?)\s*([\d,]+\.?\d*)/
    );
    if (vatMatch) {
      vatAmount = parseFloat(vatMatch[2].replace(/,/g, ""));
    }
    if (vatAmount === 0) {
      // Reversed: '136.09₪ :%00.81 מ"עמ'
      const vatRevMatch = text.match(
        /([\d,]+\.?\d*)\s*₪?\s*:?\s*%[\d.]+\s+מ"עמ/
      );
      if (vatRevMatch) {
        vatAmount = parseFloat(vatRevMatch[1].replace(/,/g, ""));
      }
    }

    // Grand total: 'סה"כ: ₪892.15' (the final total line)
    // Strategy: find all numbers near 'סה"כ' patterns.
    // The grand total is the last 'סה"כ' match that differs from the pre-VAT total.
    const grandTotalMatches = [
      ...text.matchAll(/סה"כ[:\s]*(₪?)\s*([\d,]+\.?\d*)/g),
    ];
    for (let i = grandTotalMatches.length - 1; i >= 0; i--) {
      const val = parseFloat(grandTotalMatches[i][2].replace(/,/g, ""));
      if (val > 0 && val !== preVatTotal) {
        grandTotal = val;
        break;
      }
    }

    // Reversed grand total: look for 'כ"הס' near numbers
    if (grandTotal === 0) {
      const grandRevMatches = [
        ...text.matchAll(/([\d,]+\.?\d*)\s*₪?\s*:?\s*כ"הס/g),
      ];
      for (let i = grandRevMatches.length - 1; i >= 0; i--) {
        const val = parseFloat(grandRevMatches[i][1].replace(/,/g, ""));
        if (val > 0 && val !== preVatTotal) {
          grandTotal = val;
          break;
        }
      }
    }

    // If we have pre-VAT and VAT but no grand total, calculate it
    if (grandTotal === 0 && preVatTotal > 0 && vatAmount > 0) {
      grandTotal = preVatTotal + vatAmount;
    }

    // If we have grand total and VAT but no pre-VAT, calculate it
    if (preVatTotal === 0 && grandTotal > 0 && vatAmount > 0) {
      preVatTotal = grandTotal - vatAmount;
    }

    // If we only have grand total, estimate pre-VAT (18% VAT)
    if (preVatTotal === 0 && grandTotal > 0) {
      preVatTotal = Math.round((grandTotal / 1.18) * 100) / 100;
      warnings.push("סכום לפני מע\"מ חושב מהסכום הכולל (18% מע\"מ)");
    }

    // ---------------------------------------------------------------
    // Line items extraction (best-effort)
    // ---------------------------------------------------------------
    const lineItems: ClientParsedLineItem[] = [];

    // Look for line items with מק"ט code pattern: "NNNN: description"
    const lineItemPattern = /(\d{1,5}):\s*([\u0590-\u05FF\s_\w"']+)/g;
    let itemMatch;
    while ((itemMatch = lineItemPattern.exec(text)) !== null) {
      const description = itemMatch[2].trim();
      if (description.length > 2) {
        lineItems.push({
          date: null,
          description: `${itemMatch[1]}: ${description}`,
          amount: 0, // Individual amounts are hard to reliably extract
          commission: 0,
        });
      }
    }

    // ---------------------------------------------------------------
    // Validation
    // ---------------------------------------------------------------
    if (preVatTotal === 0 && grandTotal === 0) {
      // Last resort: find the largest numbers in the document
      const allNumbers = [...text.matchAll(/([\d,]+\.\d{2})/g)]
        .map((m) => parseFloat(m[1].replace(/,/g, "")))
        .filter((n) => n > 0);

      if (allNumbers.length > 0) {
        allNumbers.sort((a, b) => b - a);
        grandTotal = allNumbers[0];
        // Second largest is likely the pre-VAT total
        if (allNumbers.length > 1) {
          preVatTotal = allNumbers[1];
        }
        warnings.push("הסכומים חולצו מהמספר הגדול ביותר במסמך - יש לאמת");
      } else {
        errors.push("לא נמצאו סכומים בחשבונית משלוחה");
        return { success: false, data: null, errors, warnings };
      }
    }

    if (!franchiseeName) {
      warnings.push("לא זוהה שם הזכיין מהמסמך");
    }

    if (!periodMonth) {
      warnings.push("לא זוהתה תקופת החשבונית");
    }

    return {
      success: true,
      data: {
        franchiseeName: franchiseeName || "לא זוהה",
        totalAmount: preVatTotal,
        commissionAmount: preVatTotal, // The entire invoice IS the commission charge
        commissionRate: 0, // Not percentage-based; flat service charges
        netAmount: grandTotal || preVatTotal, // Total incl. VAT
        periodMonth,
        periodYear,
        lineItems:
          lineItems.length > 0
            ? lineItems
            : [
                {
                  date: null,
                  description: `חשבונית מס ${invoiceNumber || "משלוחה"}`,
                  amount: preVatTotal,
                  commission: preVatTotal,
                },
              ],
        rawText: text,
      },
      errors,
      warnings,
    };
  } catch (error) {
    errors.push(
      `שגיאה בקריאת PDF משלוחה: ${error instanceof Error ? error.message : String(error)}`
    );
    return { success: false, data: null, errors, warnings };
  }
}
