/**
 * Mishloha (משלוחה) invoice parser
 *
 * Mishloha invoices are generated by ezcount.co.il (jsPDF) as image-based PDFs
 * with NO text layer. We extract the image from the PDF, run OCR (tesseract.js),
 * and parse the resulting text.
 *
 * Invoice structure (from franchisee TO Mishloha):
 * - Header: franchisee name, tax ID, address
 * - Recipient: משלוחה (דיב אנד רד פרודקטס בעמ)
 * - Invoice number, allocation number, date
 * - Line items: online orders, credit commission, customer compensation
 * - Subtotal before VAT, VAT %, total incl VAT
 */

import type { ClientDocumentProcessingResult } from "./types";

// eslint-disable-next-line @typescript-eslint/no-require-imports
const sharp = require("sharp");

/**
 * Dynamic imports that bypass Turbopack static analysis.
 * Turbopack resolves string-literal imports at build time and fails
 * on WASM/ESM packages. Using variables prevents static resolution.
 */
const PDFJS_MODULE = "pdfjs-dist/legacy/build/pdf.mjs";
const TESSERACT_MODULE = "tesseract.js";

async function loadPdfjs() {
  return import(/* webpackIgnore: true */ PDFJS_MODULE);
}

async function loadTesseract() {
  return import(/* webpackIgnore: true */ TESSERACT_MODULE);
}

/**
 * Extract the first image from a jsPDF-generated PDF.
 * Uses pdfjs-dist to parse the PDF and extract raw image data,
 * then sharp to convert to PNG buffer for OCR.
 */
async function extractImageFromPDF(buffer: Buffer): Promise<Buffer | null> {
  const pdfjsLib = await loadPdfjs();

  const doc = await pdfjsLib.getDocument({ data: new Uint8Array(buffer) })
    .promise;
  const page = await doc.getPage(1);
  const ops = await page.getOperatorList();

  const OPS = pdfjsLib.OPS;
  for (let i = 0; i < ops.fnArray.length; i++) {
    if (ops.fnArray[i] === OPS.paintImageXObject) {
      const imgName = ops.argsArray[i][0] as string;
      const imgData = page.objs.get(imgName) as {
        width: number;
        height: number;
        data: Uint8ClampedArray;
        kind: number;
      } | null;

      if (imgData?.data) {
        // kind=2 = RGB, kind=1 = RGBA
        const channels = imgData.kind === 1 ? 4 : 3;
        const pngBuffer = await sharp(Buffer.from(imgData.data), {
          raw: {
            width: imgData.width,
            height: imgData.height,
            channels: channels as 3 | 4,
          },
        })
          .png()
          .toBuffer();
        return pngBuffer;
      }
    }
  }
  return null;
}

/**
 * Run OCR on an image buffer using tesseract.js with Hebrew + English.
 */
async function ocrImage(imageBuffer: Buffer): Promise<string> {
  const tess = await loadTesseract();
  const { data } = await tess.recognize(imageBuffer, "heb+eng");
  return data.text;
}

export async function parseMishlohaFile(
  buffer: Buffer,
  mimeType: string
): Promise<ClientDocumentProcessingResult> {
  const errors: string[] = [];
  const warnings: string[] = [];

  try {
    // Step 1: Try pdf-parse for text-based PDFs
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const pdfParse = require("pdf-parse");
    const pdfData = await pdfParse(buffer);
    let text = (pdfData.text as string).trim();

    // Step 2: If no text, extract image and OCR
    if (text.length < 30) {
      const imageBuffer = await extractImageFromPDF(buffer);
      if (!imageBuffer) {
        errors.push("לא ניתן לחלץ תמונה מקובץ ה-PDF של משלוחה");
        return { success: false, data: null, errors, warnings };
      }

      text = await ocrImage(imageBuffer);
      if (text.length < 30) {
        errors.push("OCR לא הצליח לחלץ טקסט מחשבונית משלוחה");
        return { success: false, data: null, errors, warnings };
      }
    }

    return parseInvoiceText(text, warnings);
  } catch (error) {
    errors.push(
      `שגיאה בקריאת חשבונית משלוחה: ${error instanceof Error ? error.message : String(error)}`
    );
    return { success: false, data: null, errors, warnings };
  }
}

/**
 * Parse the OCR/text output of a Mishloha invoice.
 */
function parseInvoiceText(
  text: string,
  warnings: string[]
): ClientDocumentProcessingResult {
  const errors: string[] = [];

  // ── Franchisee name: first line with בע"מ ──
  let franchiseeName = "";
  const bizNameMatch = text.match(
    /([\u0590-\u05FF][\u0590-\u05FF\s"'״]{2,}(?:בע"מ|בעמ|בע״מ))/
  );
  if (bizNameMatch) {
    franchiseeName = bizNameMatch[1].trim();
  }

  // ── Invoice number ──
  let invoiceNumber = "";
  const invoiceMatch = text.match(/חשבונית\s+מס\s+מספר\s+(\d+)/);
  if (invoiceMatch) {
    invoiceNumber = invoiceMatch[1];
  }

  // ── Date → period ──
  let periodMonth: number | undefined;
  let periodYear: number | undefined;
  const dateMatch = text.match(/תאריך:\s*(\d{2})\/(\d{2})\/(\d{4})/);
  if (dateMatch) {
    periodMonth = parseInt(dateMatch[2]);
    periodYear = parseInt(dateMatch[3]);
  }

  // ── Total incl VAT: "סה"כ: ₪XX,XXX.XX" ──
  let totalAmount = 0;
  const totalMatch = text.match(/סה"כ:\s*₪?([\d,]+\.?\d*)/);
  if (totalMatch) {
    totalAmount = parseFloat(totalMatch[1].replace(/,/g, ""));
  }

  // ── Subtotal before VAT: "סה"כ חייב במע"מ: ₪XX,XXX.XX" ──
  let subtotalBeforeVat = 0;
  const subtotalMatch = text.match(
    /סה"כ\s+חייב\s+במע"מ:\s*₪?([\d,]+\.?\d*)/
  );
  if (subtotalMatch) {
    subtotalBeforeVat = parseFloat(subtotalMatch[1].replace(/,/g, ""));
  }

  // ── VAT: "מע"מ XX.XX%: ₪X,XXX.XX" ──
  let vatAmount = 0;
  const vatMatch = text.match(/מע"מ\s+[\d.]+%:\s*₪?([\d,]+\.?\d*)/);
  if (vatMatch) {
    vatAmount = parseFloat(vatMatch[1].replace(/,/g, ""));
  }

  // ── Online orders amount (line item) ──
  let onlineOrdersAmount = 0;
  const ordersMatch = text.match(
    /הזמנות\s+אונליין[\s\S]*?([\d,]+\.\d{2})\s+([\d,]+\.\d{2})/
  );
  if (ordersMatch) {
    onlineOrdersAmount = parseFloat(ordersMatch[2].replace(/,/g, ""));
  }

  // Fallback: if total is 0, try the largest number
  if (totalAmount === 0) {
    const allNumbers = [...text.matchAll(/([\d,]+\.\d{2})/g)].map((m) =>
      parseFloat(m[1].replace(/,/g, ""))
    );
    if (allNumbers.length > 0) {
      totalAmount = Math.max(...allNumbers);
      warnings.push("סכום כולל חולץ מהמספר הגדול ביותר במסמך");
    }
  }

  if (totalAmount === 0) {
    errors.push("לא נמצא סכום כולל בחשבונית משלוחה");
    return { success: false, data: null, errors, warnings };
  }

  return {
    success: true,
    data: {
      franchiseeName: franchiseeName || "",
      totalAmount,
      commissionAmount: 0, // This IS the invoice, no commission to extract
      commissionRate: 0,
      netAmount: subtotalBeforeVat || totalAmount,
      periodMonth,
      periodYear,
      lineItems: [
        {
          date: null,
          description: `חשבונית משלוחה${invoiceNumber ? ` מס' ${invoiceNumber}` : ""}${onlineOrdersAmount ? ` | הזמנות: ₪${onlineOrdersAmount.toLocaleString()}` : ""}`,
          amount: totalAmount,
          commission: 0,
        },
      ],
    },
    errors,
    warnings,
  };
}
